// css aplicado en el main.scss
import { DetailsContextProvider } from './context/context'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <DetailsContextProvider>
        <body className='main'>{children}</body>
      </DetailsContextProvider>
    </html>
  )
}
